//Copyright (C) 2017 Ambiesoft All rights reserved.
//
//Redistribution and use in source and binary forms, with or without
//modification, are permitted provided that the following conditions
//are met:
//1. Redistributions of source code must retain the above copyright
//notice, this list of conditions and the following disclaimer.
//2. Redistributions in binary form must reproduce the above copyright
//notice, this list of conditions and the following disclaimer in the
//documentation and/or other materials provided with the distribution.
//
//THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
//ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
//FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
//OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
//LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
//OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
//SUCH DAMAGE.

#include <windows.h>
#include <string>

#include "GetOSProductInfoAsString.h"

namespace Ambiesoft {

	std::wstring GetOSProductInfoAsString()
	{
		OSVERSIONINFOEX version_info;
		version_info.dwOSVersionInfoSize = sizeof(version_info);
		::GetVersionEx(reinterpret_cast<LPOSVERSIONINFOW>(&version_info));

		DWORD os_type = 0;
		GetProductInfo(version_info.dwMajorVersion, version_info.dwMinorVersion,
			0, 0, &os_type);

		switch (os_type)
		{
		case	PRODUCT_UNDEFINED:	return L"PRODUCT_UNDEFINED";
		case	PRODUCT_ULTIMATE:	return L"PRODUCT_ULTIMATE";
		case	PRODUCT_HOME_BASIC:	return L"PRODUCT_HOME_BASIC";
		case	PRODUCT_HOME_PREMIUM:	return L"PRODUCT_HOME_PREMIUM";
		case	PRODUCT_ENTERPRISE:	return L"PRODUCT_ENTERPRISE";
		case	PRODUCT_HOME_BASIC_N:	return L"PRODUCT_HOME_BASIC_N";
		case	PRODUCT_BUSINESS:	return L"PRODUCT_BUSINESS";
		case	PRODUCT_STANDARD_SERVER:	return L"PRODUCT_STANDARD_SERVER";
		case	PRODUCT_DATACENTER_SERVER:	return L"PRODUCT_DATACENTER_SERVER";
		case	PRODUCT_SMALLBUSINESS_SERVER:	return L"PRODUCT_SMALLBUSINESS_SERVER";
		case	PRODUCT_ENTERPRISE_SERVER:	return L"PRODUCT_ENTERPRISE_SERVER";
		case	PRODUCT_STARTER:	return L"PRODUCT_STARTER";
		case	PRODUCT_DATACENTER_SERVER_CORE:	return L"PRODUCT_DATACENTER_SERVER_CORE";
		case	PRODUCT_STANDARD_SERVER_CORE:	return L"PRODUCT_STANDARD_SERVER_CORE";
		case	PRODUCT_ENTERPRISE_SERVER_CORE:	return L"PRODUCT_ENTERPRISE_SERVER_CORE";
		case	PRODUCT_ENTERPRISE_SERVER_IA64:	return L"PRODUCT_ENTERPRISE_SERVER_IA64";
		case	PRODUCT_BUSINESS_N:	return L"PRODUCT_BUSINESS_N";
		case	PRODUCT_WEB_SERVER:	return L"PRODUCT_WEB_SERVER";
		case	PRODUCT_CLUSTER_SERVER:	return L"PRODUCT_CLUSTER_SERVER";
		case	PRODUCT_HOME_SERVER:	return L"PRODUCT_HOME_SERVER";
		case	PRODUCT_STORAGE_EXPRESS_SERVER:	return L"PRODUCT_STORAGE_EXPRESS_SERVER";
		case	PRODUCT_STORAGE_STANDARD_SERVER:	return L"PRODUCT_STORAGE_STANDARD_SERVER";
		case	PRODUCT_STORAGE_WORKGROUP_SERVER:	return L"PRODUCT_STORAGE_WORKGROUP_SERVER";
		case	PRODUCT_STORAGE_ENTERPRISE_SERVER:	return L"PRODUCT_STORAGE_ENTERPRISE_SERVER";
		case	PRODUCT_SERVER_FOR_SMALLBUSINESS:	return L"PRODUCT_SERVER_FOR_SMALLBUSINESS";
		case	PRODUCT_SMALLBUSINESS_SERVER_PREMIUM:	return L"PRODUCT_SMALLBUSINESS_SERVER_PREMIUM";
		case	PRODUCT_HOME_PREMIUM_N:	return L"PRODUCT_HOME_PREMIUM_N";
		case	PRODUCT_ENTERPRISE_N:	return L"PRODUCT_ENTERPRISE_N";
		case	PRODUCT_ULTIMATE_N:	return L"PRODUCT_ULTIMATE_N";
		case	PRODUCT_WEB_SERVER_CORE:	return L"PRODUCT_WEB_SERVER_CORE";
		case	PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT:	return L"PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT";
		case	PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY:	return L"PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY";
		case	PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING:	return L"PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING";
		case	PRODUCT_SERVER_FOUNDATION:	return L"PRODUCT_SERVER_FOUNDATION";
		case	PRODUCT_HOME_PREMIUM_SERVER:	return L"PRODUCT_HOME_PREMIUM_SERVER";
		case	PRODUCT_SERVER_FOR_SMALLBUSINESS_V:	return L"PRODUCT_SERVER_FOR_SMALLBUSINESS_V";
		case	PRODUCT_STANDARD_SERVER_V:	return L"PRODUCT_STANDARD_SERVER_V";
		case	PRODUCT_DATACENTER_SERVER_V:	return L"PRODUCT_DATACENTER_SERVER_V";
		case	PRODUCT_ENTERPRISE_SERVER_V:	return L"PRODUCT_ENTERPRISE_SERVER_V";
		case	PRODUCT_DATACENTER_SERVER_CORE_V:	return L"PRODUCT_DATACENTER_SERVER_CORE_V";
		case	PRODUCT_STANDARD_SERVER_CORE_V:	return L"PRODUCT_STANDARD_SERVER_CORE_V";
		case	PRODUCT_ENTERPRISE_SERVER_CORE_V:	return L"PRODUCT_ENTERPRISE_SERVER_CORE_V";
		case	PRODUCT_HYPERV:	return L"PRODUCT_HYPERV";
		case	PRODUCT_STORAGE_EXPRESS_SERVER_CORE:	return L"PRODUCT_STORAGE_EXPRESS_SERVER_CORE";
		case	PRODUCT_STORAGE_STANDARD_SERVER_CORE:	return L"PRODUCT_STORAGE_STANDARD_SERVER_CORE";
		case	PRODUCT_STORAGE_WORKGROUP_SERVER_CORE:	return L"PRODUCT_STORAGE_WORKGROUP_SERVER_CORE";
		case	PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE:	return L"PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE";
		case	PRODUCT_STARTER_N:	return L"PRODUCT_STARTER_N";
		case	PRODUCT_PROFESSIONAL:	return L"PRODUCT_PROFESSIONAL";
		case	PRODUCT_PROFESSIONAL_N:	return L"PRODUCT_PROFESSIONAL_N";
		case	PRODUCT_SB_SOLUTION_SERVER:	return L"PRODUCT_SB_SOLUTION_SERVER";
		case	PRODUCT_SERVER_FOR_SB_SOLUTIONS:	return L"PRODUCT_SERVER_FOR_SB_SOLUTIONS";
		case	PRODUCT_STANDARD_SERVER_SOLUTIONS:	return L"PRODUCT_STANDARD_SERVER_SOLUTIONS";
		case	PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE:	return L"PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE";
		case	PRODUCT_SB_SOLUTION_SERVER_EM:	return L"PRODUCT_SB_SOLUTION_SERVER_EM";
		case	PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM:	return L"PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM";
		case	PRODUCT_SOLUTION_EMBEDDEDSERVER:	return L"PRODUCT_SOLUTION_EMBEDDEDSERVER";
		case	PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE:	return L"PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE";
		case	PRODUCT_PROFESSIONAL_EMBEDDED:	return L"PRODUCT_PROFESSIONAL_EMBEDDED";
		case	PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT:	return L"PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT";
		case	PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL:	return L"PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL";
		case	PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC:	return L"PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC";
		case	PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC:	return L"PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC";
		case	PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE:	return L"PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE";
		case	PRODUCT_CLUSTER_SERVER_V:	return L"PRODUCT_CLUSTER_SERVER_V";
		case	PRODUCT_EMBEDDED:	return L"PRODUCT_EMBEDDED";
		case	PRODUCT_STARTER_E:	return L"PRODUCT_STARTER_E";
		case	PRODUCT_HOME_BASIC_E:	return L"PRODUCT_HOME_BASIC_E";
		case	PRODUCT_HOME_PREMIUM_E:	return L"PRODUCT_HOME_PREMIUM_E";
		case	PRODUCT_PROFESSIONAL_E:	return L"PRODUCT_PROFESSIONAL_E";
		case	PRODUCT_ENTERPRISE_E:	return L"PRODUCT_ENTERPRISE_E";
		case	PRODUCT_ULTIMATE_E:	return L"PRODUCT_ULTIMATE_E";
		case	PRODUCT_ENTERPRISE_EVALUATION:	return L"PRODUCT_ENTERPRISE_EVALUATION";
		case	PRODUCT_MULTIPOINT_STANDARD_SERVER:	return L"PRODUCT_MULTIPOINT_STANDARD_SERVER";
		case	PRODUCT_MULTIPOINT_PREMIUM_SERVER:	return L"PRODUCT_MULTIPOINT_PREMIUM_SERVER";
		case	PRODUCT_STANDARD_EVALUATION_SERVER:	return L"PRODUCT_STANDARD_EVALUATION_SERVER";
		case	PRODUCT_DATACENTER_EVALUATION_SERVER:	return L"PRODUCT_DATACENTER_EVALUATION_SERVER";
		case	PRODUCT_ENTERPRISE_N_EVALUATION:	return L"PRODUCT_ENTERPRISE_N_EVALUATION";
		case	PRODUCT_EMBEDDED_AUTOMOTIVE:	return L"PRODUCT_EMBEDDED_AUTOMOTIVE";
		case	PRODUCT_EMBEDDED_INDUSTRY_A:	return L"PRODUCT_EMBEDDED_INDUSTRY_A";
		case	PRODUCT_THINPC:	return L"PRODUCT_THINPC";
		case	PRODUCT_EMBEDDED_A:	return L"PRODUCT_EMBEDDED_A";
		case	PRODUCT_EMBEDDED_INDUSTRY:	return L"PRODUCT_EMBEDDED_INDUSTRY";
		case	PRODUCT_EMBEDDED_E:	return L"PRODUCT_EMBEDDED_E";
		case	PRODUCT_EMBEDDED_INDUSTRY_E:	return L"PRODUCT_EMBEDDED_INDUSTRY_E";
		case	PRODUCT_EMBEDDED_INDUSTRY_A_E:	return L"PRODUCT_EMBEDDED_INDUSTRY_A_E";
		case	PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER:	return L"PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER";
		case	PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER:	return L"PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER";
		case	PRODUCT_CORE_ARM:	return L"PRODUCT_CORE_ARM";
		case	PRODUCT_CORE_N:	return L"PRODUCT_CORE_N";
		case	PRODUCT_CORE_COUNTRYSPECIFIC:	return L"PRODUCT_CORE_COUNTRYSPECIFIC";
		case	PRODUCT_CORE_SINGLELANGUAGE:	return L"PRODUCT_CORE_SINGLELANGUAGE";
		case	PRODUCT_CORE:	return L"PRODUCT_CORE";
		case	PRODUCT_PROFESSIONAL_WMC:	return L"PRODUCT_PROFESSIONAL_WMC";
		case	PRODUCT_EMBEDDED_INDUSTRY_EVAL:	return L"PRODUCT_EMBEDDED_INDUSTRY_EVAL";
		case	PRODUCT_EMBEDDED_INDUSTRY_E_EVAL:	return L"PRODUCT_EMBEDDED_INDUSTRY_E_EVAL";
		case	PRODUCT_EMBEDDED_EVAL:	return L"PRODUCT_EMBEDDED_EVAL";
		case	PRODUCT_EMBEDDED_E_EVAL:	return L"PRODUCT_EMBEDDED_E_EVAL";
		case	PRODUCT_NANO_SERVER:	return L"PRODUCT_NANO_SERVER";
		case	PRODUCT_CLOUD_STORAGE_SERVER:	return L"PRODUCT_CLOUD_STORAGE_SERVER";
		case	PRODUCT_CORE_CONNECTED:	return L"PRODUCT_CORE_CONNECTED";
		case	PRODUCT_PROFESSIONAL_STUDENT:	return L"PRODUCT_PROFESSIONAL_STUDENT";
		case	PRODUCT_CORE_CONNECTED_N:	return L"PRODUCT_CORE_CONNECTED_N";
		case	PRODUCT_PROFESSIONAL_STUDENT_N:	return L"PRODUCT_PROFESSIONAL_STUDENT_N";
		case	PRODUCT_CORE_CONNECTED_SINGLELANGUAGE:	return L"PRODUCT_CORE_CONNECTED_SINGLELANGUAGE";
		case	PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC:	return L"PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC";
		case	PRODUCT_CONNECTED_CAR:	return L"PRODUCT_CONNECTED_CAR";
		case	PRODUCT_INDUSTRY_HANDHELD:	return L"PRODUCT_INDUSTRY_HANDHELD";
		case	PRODUCT_PPI_PRO:	return L"PRODUCT_PPI_PRO";
		case	PRODUCT_ARM64_SERVER:	return L"PRODUCT_ARM64_SERVER";
		case	PRODUCT_EDUCATION:	return L"PRODUCT_EDUCATION";
		case	PRODUCT_EDUCATION_N:	return L"PRODUCT_EDUCATION_N";
		case	PRODUCT_IOTUAP:	return L"PRODUCT_IOTUAP";
		case	PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER:	return L"PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER";
		case	PRODUCT_ENTERPRISE_S:	return L"PRODUCT_ENTERPRISE_S";
		case	PRODUCT_ENTERPRISE_S_N:	return L"PRODUCT_ENTERPRISE_S_N";
		case	PRODUCT_PROFESSIONAL_S:	return L"PRODUCT_PROFESSIONAL_S";
		case	PRODUCT_PROFESSIONAL_S_N:	return L"PRODUCT_PROFESSIONAL_S_N";
		case	PRODUCT_ENTERPRISE_S_EVALUATION:	return L"PRODUCT_ENTERPRISE_S_EVALUATION";
		case	PRODUCT_ENTERPRISE_S_N_EVALUATION:	return L"PRODUCT_ENTERPRISE_S_N_EVALUATION";
		case	PRODUCT_HOLOGRAPHIC:	return L"PRODUCT_HOLOGRAPHIC";
		case	PRODUCT_HOLOGRAPHIC_BUSINESS:	return L"PRODUCT_HOLOGRAPHIC_BUSINESS";
		case	PRODUCT_PRO_SINGLE_LANGUAGE:	return L"PRODUCT_PRO_SINGLE_LANGUAGE";
		case	PRODUCT_PRO_CHINA:	return L"PRODUCT_PRO_CHINA";
		case	PRODUCT_ENTERPRISE_SUBSCRIPTION:	return L"PRODUCT_ENTERPRISE_SUBSCRIPTION";
		case	PRODUCT_ENTERPRISE_SUBSCRIPTION_N:	return L"PRODUCT_ENTERPRISE_SUBSCRIPTION_N";
		case	PRODUCT_DATACENTER_NANO_SERVER:	return L"PRODUCT_DATACENTER_NANO_SERVER";
		case	PRODUCT_STANDARD_NANO_SERVER:	return L"PRODUCT_STANDARD_NANO_SERVER";
		case	PRODUCT_DATACENTER_A_SERVER_CORE:	return L"PRODUCT_DATACENTER_A_SERVER_CORE";
		case	PRODUCT_STANDARD_A_SERVER_CORE:	return L"PRODUCT_STANDARD_A_SERVER_CORE";
		case	PRODUCT_DATACENTER_WS_SERVER_CORE:	return L"PRODUCT_DATACENTER_WS_SERVER_CORE";
		case	PRODUCT_STANDARD_WS_SERVER_CORE:	return L"PRODUCT_STANDARD_WS_SERVER_CORE";
		case	PRODUCT_UTILITY_VM:	return L"PRODUCT_UTILITY_VM";
		case	PRODUCT_DATACENTER_EVALUATION_SERVER_CORE:	return L"PRODUCT_DATACENTER_EVALUATION_SERVER_CORE";
		case	PRODUCT_STANDARD_EVALUATION_SERVER_CORE:	return L"PRODUCT_STANDARD_EVALUATION_SERVER_CORE";
		case	PRODUCT_PRO_WORKSTATION:	return L"PRODUCT_PRO_WORKSTATION";
		case	PRODUCT_PRO_WORKSTATION_N:	return L"PRODUCT_PRO_WORKSTATION_N";
		case	PRODUCT_PRO_FOR_EDUCATION:	return L"PRODUCT_PRO_FOR_EDUCATION";
		case	PRODUCT_PRO_FOR_EDUCATION_N:	return L"PRODUCT_PRO_FOR_EDUCATION_N";
		case	PRODUCT_AZURE_SERVER_CORE:	return L"PRODUCT_AZURE_SERVER_CORE";
		case	PRODUCT_AZURE_NANO_SERVER:	return L"PRODUCT_AZURE_NANO_SERVER";
		case	PRODUCT_ENTERPRISEG:	return L"PRODUCT_ENTERPRISEG";
		case	PRODUCT_ENTERPRISEGN:	return L"PRODUCT_ENTERPRISEGN";
		case	PRODUCT_SERVERRDSH:	return L"PRODUCT_SERVERRDSH";
		case	PRODUCT_CLOUD:	return L"PRODUCT_CLOUD";
		case	PRODUCT_CLOUDN:	return L"PRODUCT_CLOUDN";
		case	PRODUCT_HUBOS:	return L"PRODUCT_HUBOS";
		case	PRODUCT_ONECOREUPDATEOS:	return L"PRODUCT_ONECOREUPDATEOS";
		case	PRODUCT_CLOUDE:	return L"PRODUCT_CLOUDE";
		case	PRODUCT_IOTOS:	return L"PRODUCT_IOTOS";
		case	PRODUCT_CLOUDEN:	return L"PRODUCT_CLOUDEN";
		case	PRODUCT_IOTEDGEOS:	return L"PRODUCT_IOTEDGEOS";
		case	PRODUCT_IOTENTERPRISE:	return L"PRODUCT_IOTENTERPRISE";
		case	PRODUCT_LITE:	return L"PRODUCT_LITE";
		case	PRODUCT_IOTENTERPRISES:	return L"PRODUCT_IOTENTERPRISES";
		case	PRODUCT_XBOX_SYSTEMOS:	return L"PRODUCT_XBOX_SYSTEMOS";
		case	PRODUCT_XBOX_GAMEOS:	return L"PRODUCT_XBOX_GAMEOS";
		case	PRODUCT_XBOX_ERAOS:	return L"PRODUCT_XBOX_ERAOS";
		case	PRODUCT_XBOX_DURANGOHOSTOS:	return L"PRODUCT_XBOX_DURANGOHOSTOS";
		case	PRODUCT_XBOX_SCARLETTHOSTOS:	return L"PRODUCT_XBOX_SCARLETTHOSTOS";
		case	PRODUCT_XBOX_KEYSTONE:	return L"PRODUCT_XBOX_KEYSTONE";
		case	PRODUCT_AZURE_SERVER_CLOUDHOST:	return L"PRODUCT_AZURE_SERVER_CLOUDHOST";
		case	PRODUCT_AZURE_SERVER_CLOUDMOS:	return L"PRODUCT_AZURE_SERVER_CLOUDMOS";
		case	PRODUCT_CLOUDEDITIONN:	return L"PRODUCT_CLOUDEDITIONN";
		case	PRODUCT_CLOUDEDITION:	return L"PRODUCT_CLOUDEDITION";
		case	PRODUCT_AZURESTACKHCI_SERVER_CORE:	return L"PRODUCT_AZURESTACKHCI_SERVER_CORE";
		case	PRODUCT_DATACENTER_SERVER_AZURE_EDITION:	return L"PRODUCT_DATACENTER_SERVER_AZURE_EDITION";
		case	PRODUCT_DATACENTER_SERVER_CORE_AZURE_EDITION:	return L"PRODUCT_DATACENTER_SERVER_CORE_AZURE_EDITION";
		case	PRODUCT_UNLICENSED:	return L"PRODUCT_UNLICENSED";
		}
		return L"PRODUCT_UNKNOWN";
	}

}